import ENVIRONMENT from './ENVIRONMENT';

const PROTOCOL = ENVIRONMENT.HTTPS ? 'https://' : 'http://';
const DOMAIN = ENVIRONMENT.DOMAIN;

const SERVER_URL_WITH_PROTOCOL = `${PROTOCOL}${ENVIRONMENT.SERVER_URL}`;
const CLIENT_URL_WITH_PROTOCOL = `${PROTOCOL}${ENVIRONMENT.CLIENT_URL}`;

const SERVER_PORT = ENVIRONMENT.SERVER_PORT;
const CLIENT_PORT = ENVIRONMENT.CLIENT_PORT;

const SERVER_FULL_URL =
  ENVIRONMENT.MODE.toUpperCase() === 'DEVELOPMENT'
    ? `${SERVER_URL_WITH_PROTOCOL}:${SERVER_PORT}`
    : SERVER_URL_WITH_PROTOCOL;
export const CLIENT_FULL_URL =
  ENVIRONMENT.MODE.toUpperCase() === 'PRODUCTION'
    ? CLIENT_URL_WITH_PROTOCOL
    : `${CLIENT_URL_WITH_PROTOCOL}:${CLIENT_PORT}`;

export const API_BASE = '';
export const API_URL = `${SERVER_FULL_URL}${API_BASE}`;

const ENDPOINTS = {
  EXAMPLE: '/example',
};

const API_ENDPOINTS = {
  COUNTRIES:'/countries',
  EXAMPLE: {
    test: `${ENDPOINTS.EXAMPLE}/test`,
  },
};

const URLS = {
  MAIN_URLS: {
    CLIENT_PORT,
    CLIENT_URL_WITH_PROTOCOL,
    SERVER_PORT,
    SERVER_URL_WITH_PROTOCOL,
    API_URL,
    CLIENT_FULL_URL,
    SERVER_FULL_URL,
    DOMAIN,
  },
  ENDPOINTS: API_ENDPOINTS,
};

export default URLS;
